kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  storageClassName: ""
  claimRef:
    name: pvmysql
    namespace: mssql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
