---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvmssql 
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" 

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  storageClassName: manual
  volume: pvmysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
